import type { PoolClient } from "pg";
import { pool } from "./db.js";
import { randomUUID } from "node:crypto";

const MAX_ROOM_PLAYERS = 8;
const LETTERS = "AAAAAAAAABBCCCDDEEEEEEEEEEEFFGGGHHHHIIIIIJKLLLLMNNNNNOOOOOOOOPPQQRRRRRSSSSSTTTTTTUUUUVVWWXYYZ";

export type RoomPlayer = { playerId:string; seatNumber:number; connected:boolean; score:number };
export type RoomSnapshot = { type:"room_snapshot"; roomId:string; eventSequence:number; state:"waiting"|"active"|"finished"; phase:"waiting"|"playing"|"solve_window"|"round_end"|"finished"; roundNumber:number; turnNumber:number; activePlayerId:string|null; firstSolverId:string|null; solvedAt:string|null; solveWindowEndsAt:string|null; serverTime:string; players:RoomPlayer[] };
export type DisconnectHooks = { beforeDisconnectUpdate?:()=>Promise<void>; afterDisconnectUpdate?:(rowCount:number)=>void };
export type RoomEvent = { type:"event"; eventSequence:number; roomId:string; roundNumber:number; eventType:"room_created"|"player_joined"|"word_submitted"|"round_completed"; serverTime:string; payload:Record<string,unknown> };

function toSnapshot(room:Record<string,any>,players:Array<Record<string,any>>):RoomSnapshot{return{type:"room_snapshot",roomId:room.id,eventSequence:Number(room.event_sequence),state:room.state,phase:room.phase,roundNumber:room.round_number,turnNumber:Number(room.turn_number),activePlayerId:room.active_player_id,firstSolverId:room.first_solver_id,solvedAt:room.solved_at?new Date(room.solved_at).toISOString():null,solveWindowEndsAt:room.solve_window_ends_at?new Date(room.solve_window_ends_at).toISOString():null,serverTime:new Date().toISOString(),players:players.map(p=>({playerId:p.player_id,seatNumber:p.seat_number,connected:p.connected,score:p.score}))};}
async function readSnapshot(client:PoolClient,roomId:string):Promise<RoomSnapshot>{const room=await client.query(`SELECT id,state,phase,round_number,turn_number,active_player_id,event_sequence,first_solver_id,solved_at,solve_window_ends_at FROM public.game_rooms WHERE id=$1`,[roomId]);const players=await client.query(`SELECT player_id,seat_number,connected,score FROM public.room_players WHERE room_id=$1 ORDER BY seat_number`,[roomId]);if(room.rowCount!==1)throw new Error("room_not_found");return toSnapshot(room.rows[0],players.rows);}
async function appendEvent(client:PoolClient,roomId:string,roundNumber:number,eventType:RoomEvent["eventType"],payload:Record<string,unknown>):Promise<RoomEvent>{const next=await client.query(`UPDATE public.game_rooms SET event_sequence=event_sequence+1,updated_at=clock_timestamp() WHERE id=$1 RETURNING event_sequence`,[roomId]);const sequence=Number(next.rows[0].event_sequence);const inserted=await client.query(`INSERT INTO public.room_events(room_id,event_sequence,round_number,event_type,payload) VALUES($1,$2,$3,$4,$5::jsonb) RETURNING created_at`,[roomId,sequence,roundNumber,eventType,JSON.stringify(payload)]);return{type:"event",eventSequence:sequence,roomId,roundNumber,eventType,serverTime:new Date(inserted.rows[0].created_at).toISOString(),payload};}
function makeHand():Array<{cardId:string;value:string}>{const poolLetters=LETTERS.split("");const hand=[];for(let i=0;i<14;i++){const index=Math.floor(Math.random()*poolLetters.length);hand.push({cardId:randomUUID(),value:poolLetters.splice(index,1)[0].toLowerCase()});}return hand;}
export async function createRoom(playerId:string):Promise<{snapshot:RoomSnapshot;events:RoomEvent[]}>{const client=await pool.connect();try{await client.query("BEGIN");const room=await client.query(`INSERT INTO public.game_rooms(state,phase) VALUES('waiting','waiting') RETURNING id`);const roomId=room.rows[0].id as string;await client.query(`INSERT INTO public.room_players(room_id,player_id,seat_number,connected,turn_state) VALUES($1,$2,0,true,'waiting')`,[roomId,playerId]);const event=await appendEvent(client,roomId,1,"room_created",{playerId});const snapshot=await readSnapshot(client,roomId);await client.query("COMMIT");return{snapshot,events:[event]};}catch(e){await client.query("ROLLBACK");throw e;}finally{client.release();}}
export async function startRound(roomId:string):Promise<RoomSnapshot>{const client=await pool.connect();try{await client.query("BEGIN");const room=await client.query(`SELECT id,state,phase,round_number,turn_number FROM public.game_rooms WHERE id=$1 FOR UPDATE`,[roomId]);if(room.rowCount!==1)throw new Error("room_not_found");if(room.rows[0].phase!=="waiting")throw new Error("round_already_started");const players=await client.query(`SELECT player_id FROM public.room_players WHERE room_id=$1 ORDER BY seat_number FOR UPDATE`,[roomId]);if((players.rowCount??0)<2)throw new Error("not_enough_players");const starter=players.rows[0].player_id;for(const p of players.rows){await client.query(`UPDATE public.room_players SET private_hand=$2::jsonb,hand_version=1,hand_round_number=$3,turn_state=CASE WHEN player_id=$4 THEN 'active' ELSE 'waiting' END,updated_at=clock_timestamp() WHERE room_id=$1 AND player_id=$4`,[roomId,JSON.stringify(makeHand()),Number(room.rows[0].round_number),p.player_id]);}await client.query(`UPDATE public.game_rooms SET state='active',phase='playing',active_player_id=$2,updated_at=clock_timestamp() WHERE id=$1`,[roomId,starter]);const snapshot=await readSnapshot(client,roomId);await client.query("COMMIT");return snapshot;}catch(e){await client.query("ROLLBACK");throw e;}finally{client.release();}}
export async function getPrivateHand(roomId:string,playerId:string):Promise<{hand:Array<{cardId:string;value:string}>;handVersion:number;roundNumber:number}>{const result=await pool.query(`SELECT private_hand,hand_version,hand_round_number FROM public.room_players WHERE room_id=$1 AND player_id=$2`,[roomId,playerId]);if(result.rowCount!==1)throw new Error("player_not_in_room");return{hand:Array.isArray(result.rows[0].private_hand)?result.rows[0].private_hand:[],handVersion:Number(result.rows[0].hand_version),roundNumber:Number(result.rows[0].hand_round_number)};}
export async function resumeRoom(roomId:string,playerId:string):Promise<{snapshot:RoomSnapshot;connectionVersion:number;handVersion:number}>{const client=await pool.connect();try{await client.query("BEGIN");const room=await client.query(`SELECT id FROM public.game_rooms WHERE id=$1 FOR UPDATE`,[roomId]);if(room.rowCount!==1)throw new Error("room_not_found");const player=await client.query(`SELECT player_id,hand_version FROM public.room_players WHERE room_id=$1 AND player_id=$2 FOR UPDATE`,[roomId,playerId]);if(player.rowCount!==1)throw new Error("player_not_in_room");const resumed=await client.query(`UPDATE public.room_players SET connected=true,connection_version=connection_version+1,updated_at=clock_timestamp() WHERE room_id=$1 AND player_id=$2 RETURNING connection_version,hand_version`,[roomId,playerId]);const snapshot=await readSnapshot(client,roomId);await client.query("COMMIT");return{snapshot,connectionVersion:Number(resumed.rows[0].connection_version),handVersion:Number(resumed.rows[0].hand_version)};}catch(e){await client.query("ROLLBACK");throw e;}finally{client.release();}}
export async function markPlayerDisconnected(roomId:string,playerId:string,connectionVersion:number,hooks:DisconnectHooks={}):Promise<number>{await hooks.beforeDisconnectUpdate?.();console.error(`[ws-disconnect] UPDATE start roomId=${roomId} playerId=${playerId} connectionVersion=${connectionVersion}`);const result=await pool.query(`UPDATE public.room_players SET connected=false,updated_at=clock_timestamp() WHERE room_id=$1 AND player_id=$2 AND connection_version=$3`,[roomId,playerId,connectionVersion]);const rowCount=result.rowCount??0;console.error(`[ws-disconnect] UPDATE complete roomId=${roomId} playerId=${playerId} connectionVersion=${connectionVersion} matchedRowCount=${rowCount}`);hooks.afterDisconnectUpdate?.(rowCount);return rowCount;}
export async function joinRoom(roomId:string,playerId:string):Promise<{snapshot:RoomSnapshot;events:RoomEvent[]}>{const client=await pool.connect();try{await client.query("BEGIN");const room=await client.query(`SELECT id,state,phase,round_number FROM public.game_rooms WHERE id=$1 FOR UPDATE`,[roomId]);if(room.rowCount!==1)throw new Error("room_not_found");if(room.rows[0].state!=="waiting")throw new Error("room_not_joinable");const count=await client.query(`SELECT count(*) AS count FROM public.room_players WHERE room_id=$1`,[roomId]);if(Number(count.rows[0].count)>=MAX_ROOM_PLAYERS)throw new Error("room_full");const existing=await client.query(`SELECT player_id FROM public.room_players WHERE room_id=$1 AND player_id=$2`,[roomId,playerId]);if(existing.rowCount)throw new Error("player_already_in_room");const seat=await client.query(`SELECT COALESCE(MAX(seat_number)+1,0) AS next_seat FROM public.room_players WHERE room_id=$1`,[roomId]);const seatNumber=Number(seat.rows[0].next_seat);await client.query(`INSERT INTO public.room_players(room_id,player_id,seat_number,connected,turn_state) VALUES($1,$2,$3,true,'waiting')`,[roomId,playerId,seatNumber]);const event=await appendEvent(client,roomId,Number(room.rows[0].round_number),"player_joined",{playerId,seatNumber});const snapshot=await readSnapshot(client,roomId);await client.query("COMMIT");return{snapshot,events:[event]};}catch(e){await client.query("ROLLBACK");throw e;}finally{client.release();}}
